name: Backend CI
on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff mypy pytest
      - name: Ruff
        working-directory: backend
        run: ruff check . || true
      - name: Black (check)
        working-directory: backend
        run: black --check . || true
      - name: Mypy
        working-directory: backend
        run: mypy app || true
      - name: Pytest
        working-directory: backend
        run: pytest -q || true

