name: Frontend CI
on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
      - name: Install deps
        working-directory: frontend
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        working-directory: frontend
        run: pnpm typecheck
      - name: Lint
        working-directory: frontend
        run: pnpm run -s lint
      - name: Test
        working-directory: frontend
        run: pnpm test -- --ci

