name: Performance Baseline (Locust)

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  locust:
    name: Locust Headless Baseline
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      backend-db:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: testuser
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb
        run: |
          alembic upgrade head || echo "Skipping migrations if not configured"

      - name: Start backend server
        env:
          DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb
          TESTING: true
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 10

      - name: Run Locust (headless short run)
        env:
          BASE_URL: http://localhost:8000
        run: |
          mkdir -p perf-artifacts
          locust -f scripts/locustfile.py --headless -u 5 -r 2 -t 1m --host http://localhost:8000 --html perf-artifacts/report.html || true

      - name: Upload Locust Report
        uses: actions/upload-artifact@v4
        with:
          name: locust-report
          path: backend/perf-artifacts

